### ISSUE TITLE
Scals 2.13 support

### ISSUE THREAD

**Issue by jtjeferreira** [tek/splain#22]
Hi, thanks for this great plugin! Any change to support scala 2.13.0-M5?

**Comment by tek** [comment]
thank you! :smile: 
0.4.0 is in the process of being published, please report back whether it works for you!

**Comment by jtjeferreira** [comment]
I tried to do this but was blocked in some non backwards compatible change in the Scala compiler and one test was failing... You have a branch with that code?

**Comment by tek** [comment]
you tried publishing locally? I meant install it from maven! it's already promoted, so just change your dependency and it should be found.
the tests are indeed broken for <2.13 now, I'll need to investigate what changed in order to fix it. But since it was only a minor failure, I've published it anyway.

**Comment by tek** [comment]
just noticed that I haven't pushed the repo.
I guess you meant that you tried to create a PR but failed at the test!
in any case, my previous comment still holds :smile:

**Comment by jtjeferreira** [comment]
Yes I was looking for the code changes :p

**Comment by tek** [comment]
they're there now :laughing:
